import { StyleSheet } from 'react-native';
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';
import { StatusBar } from 'react-native';
export const stylesBodyHome = StyleSheet.create({
    container: {
        height: hp('80%')-StatusBar.currentHeight,
        width: wp('100%'),
        alignItems: 'center',
    },
    containerFromTo:{
        height: hp('35%'),
        width: wp('95%'),
        borderWidth: 1,
        borderRadius: 12,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 8,
        marginTop: 10,
        backgroundColor:'#f26222',
        flexDirection:'row',
        
    },
    containerFrom:{
        height: hp('35%'),
        width: wp('47.5%'),
        flexDirection: 'column',
        textAlign:'center',
        alignItems:'center',
        // borderRightWidth:1,
        // borderColor:'#ffffff',
        justifyContent: 'center',
    },
    containerTo:{
        height: hp('35%'),
        width: wp('47.5%'),
        flexDirection: 'column',
        textAlign:'center',
        alignItems:'center',
        // borderLeftWidth:1,
        // borderColor:'#ffffff',
        justifyContent: 'center',
    },
    txtTitle : {
        color:'#ffffff',
        fontWeight: 'bold',
        fontSize: hp('3%'),
        borderBottomColor: '#ffffff',
        borderBottomWidth: 1,
    },
    txtMS:{
        color:'#ffffff',
        fontSize: hp('7%'),
    },
    txtTen:{
        color:'#ffffff',
        fontSize: hp('3%'),
    },
    containerDateStart:{
        height: hp('10%'),
        width: wp('47.5%'),
        borderWidth: 1,
        borderRadius: 4,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 8,
        marginTop: 10,
        marginRight:wp("1.25%"),
        backgroundColor:'#ffffff'
    },
    containerDateEnd:{
        height: hp('10%'),
        width: wp('45%'),
        borderWidth: 1,
        borderRadius: 4,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 8,
        marginTop: 10,
        backgroundColor:'#ffffff',
        marginLeft:wp("1.25%"),
    }
});